compel/plugins/std: use sys_recvfrom instead of recv
As recv is library function, not a syscall:
compel/plugins/std/std.c:41:8: error: implicit declaration of function ‘sys_recv’ [-Werror=implicit-function-declaration]
  ret = sys_recv(ctl_socket, buf, sizeof(buf), MSG_WAITALL);

Signed-off-by: Dmitry Safonov <dsafonov@virtuozzo.com>